name:                haskell-workshop
version:             0.1.0.0
github:              "mariatsji/haskell-workshop"
license:             BSD3
author:              "Sjur Millidahl"
maintainer:          "sjur.millidahl@gmail.com"
copyright:           "BSD-3-Clause"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mariatsji/haskell-workshop#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  haskell-workshop:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-workshop

tests:
  haskell-workshop-test:
    main:                Part1Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-workshop
    - tasty
    - tasty-quickcheck
    - tasty-hspec
    - hspec
